source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod "Dispatcher", :path => "../"

target 'Dispatcher_Example', :exclusive => true do
end

target 'Dispatcher_Tests', :exclusive => true do
end
